In [1]:
import pandas as pd

In [2]:
dados_socio = pd.read_csv("dados-socio-economicos-20171", sep=';')
dados_socio.dropna()

,id_discente,ano,periodo,renda,escola_ens_medio,possui_bolsa_pesquisa,possui_auxilio_alimentacao,possui_auxilio_transporte,possui_auxilio_residencia_moradia
0,9098c14ef1ad865247b2abda52806775,2017,1,2000.0,Todo em escola particular,f,f,f,f
1,694c169b65f2043aa95138e0037c8908,2017,1,3000.0,Todo em escola publica,f,f,f,f
2,bdd599acd452057916e6b4f177baf6a9,2017,1,1000.0,Todo em escola publica,f,f,f,f
3,430241bbd7a5248f09e6994995a33f3b,2017,1,3200.0,Todo em escola particular,f,f,f,f
4,cf43986a0745aa181201a9df000d5368,2017,1,4600.0,Todo em escola publica,f,f,f,f
5,e6c6a2cf710c27fe7c723c6fc8637624,2017,1,4500.0,Todo em escola publica,f,f,f,f
6,c80db7072a2416442aff28c2b6bce61f,2017,1,1448.0,Todo em escola publica,f,t,f,f
7,7210dc39996acda1c74a7d7343b6715b,2017,1,3098.0,Todo em escola particular,f,t,f,f
8,2abcedcdc34c4f16b7514673db67221f,2017,1,1240.0,Todo em escola publica,f,t,f,t
9,4c7b1574824787ab23c84062a1814ea5,2017,1,900.0,Todo em escola publica,f,t,f,t
10,375380f65c8a6a91972fd11a044cb0a9,2017,1,937.0,Todo em escola publica,f,t,f,f
11,5e7b890f9d1e141f34784928f1ca5735,2017,1,2848.0,Todo em escola particular,f,f,f,f
12,9b0cf322d76f570faab426f9eadad163,2017,1,2811.0,Todo em escola publica,f,f,f,f
13,f88d82964a40087e578fd16ae8a6c998,2017,1,2285.0,Todo em escola publica,f,t,f,f
14,59c18d2c5031c04c6f34e530187734c3,2017,1,880.0,Todo em escola publica,f,t,f,t
15,b0cfefb73bcc5b08e4a8a33c6cb6e67c,2017,1,744.0,Todo em escola publica,f,f,f,f
16,e20bfce3b9490e299a84ffc7ae80f237,2017,1,3000.0,Todo em escola particular,f,f,t,f
17,88902410e1c28d772a1202f1656b4fb3,2017,1,8500.0,Todo em escola publica,f,f,t,f
18,a8fd73f6db7899825cdfa1656f9d6a45,2017,1,1200.0,Todo em escola publica,f,t,f,f
19,99621b0d5f7cf431df775dd2f2a3d636,2017,1,2200.0,Todo em escola publica,f,f,f,f
20,624b979c48328c7c514790faedba547a,2017,1,1760.0,Todo em escola publica,f,f,f,f
21,ec41f08e7ef8fa58fc5668733ad0260b,2017,1,3700.0,Todo em escola publica,f,f,f,f
22,a2323da38a5ac71952c550e094f30f09,2017,1,3777.0,Todo em escola publica,f,t,f,f
23,34424b90aaa4dbab02145cbf392c1dc5,2017,1,900.0,Outro tipo de escola,f,f,f,f
24,7ba3bf9d46e6e93f48807d54e724882d,2017,1,6000.0,Parte em escola pública parte em escola partic...,f,f,f,f
25,b73bb592e67ac3ecbf4da629258c6019,2017,1,5680.0,Todo em escola particular,f,f,f,f
26,9599863c9076694f25e3af358aa920c4,2017,1,1116.0,Todo em escola publica,f,f,f,f
27,19c810f862e575a3d97b1d01b0d07dbf,2017,1,3000.0,Todo em escola publica,f,f,f,f
28,a2e71a218149b801a7611c9743f83a6c,2017,1,880.0,Todo em escola publica,f,t,f,f
29,4d4f7c4df7d24bcc505ec8569e46f8fb,2017,1,880.0,Todo em escola publica,f,t,f,t
...,...,...,...,...,...,...,...,...,...
13881,b9222799dff7ab853a75fc2403241fb1,2017,1,1200.0,Todo em escola publica,f,f,f,f
13882,70f1d2af8ecb767ddc517538bbf2d8c2,2017,1,2600.0,Todo em escola particular,f,f,f,f
13883,9df15d583742aeaa05c247170a28bcbb,2017,1,583.0,Todo em escola publica,f,f,f,f
13884,dc9a10bd05e46a37ed92fc91386efbe3,2017,1,1183.0,Todo em escola publica,f,t,f,f
13885,fd27e454bc66660b0e9ceb08a6152141,2017,1,900.0,Todo em escola publica,f,t,f,t
13886,f05d0a879dd2a06be966654cdda25834,2017,1,0.0,Parte em escola pública parte em escola partic...,f,f,f,f
13887,cde170fe4f1cfaffcfe1e5ec08e362af,2017,1,1141.0,Todo em escola publica,f,t,f,t
13888,1ad4f0d3334f09a677300a4c858f8e72,2017,1,14400.0,Todo em escola particular,f,f,f,f
13889,9f9192b02aa7fad622d9ff2df1345623,2017,1,2000.0,Todo em escola publica,f,f,f,f
13890,2e3e1fa2fea9daa91c1229d80bcfb1cf,2017,1,4350.0,Todo em escola publica,t,f,f,f
13891,4472d242670e4f14231b42fd548d5b51,2017,1,1248.0,Todo em escola publica,f,f,f,f
13893,83b64df4abdee15e5442a4d9fefeebf5,2017,1,1082574.0,Todo em escola particular,f,f,f,f
13894,928426909dd70d9362c8e5db72de6da3,2017,1,800.0,Todo em escola particular,f,f,f,f
13895,65233c00ed896f32d6a66ca0a7750deb,2017,1,900.0,Todo em escola publica,f,t,f,f
13896,08676aec51622776266fa7e0ed755e94,2017,1,1280.0,Todo em escola publica,f,t,f,t
13897,c574c01136dd64feab1e0e4dfcf89b34,2017,1,4060.0,"Em escola Particular, com bolsa",f,t,f,f
13898,58a990c9d51a1bb9d91ee6fe4032c18b,2017,1,8300.0,Todo em escola publica,f,f,f,f
13899,2d29f4ec01ba736344137a1ec998dbc4,2017,1,724.0,Todo em escola publica,f,f,f,f
13900,62313017b4cf7ca4a9c56019c7021432,2017,1,847.0,Todo em escola publica,f,t,f,f
13901,89e14a1527f339c6f7e77102b89bd0c0,2017,1,1070.0,Todo em escola publica,f,f,f,f
13902,0e561bd26747c12e242b499b092da011,2017,1,124.0,Todo em escola publica,f,f,t,f
13903,aa3fd4e3c8fb69743daea0006c29f5cc,2017,1,2741.0,Todo em escola particular,f,f,f,f
13904,09f36a9eda8646f7435171c12efc90e1,2017,1,880.0,Todo em escola publica,f,f,f,f
13905,ee895caa3970d30fc23df9f373296aa8,2017,1,1150.0,Todo em escola publica,f,t,f,f
13906,edf08183011457cc8f59dd78a75653ea,2017,1,16000.0,"Em escola Particular, com bolsa",f,t,f,f
13907,2400b12c363c982e13e272dcf56708a1,2017,1,1900.0,Todo em escola publica,f,t,f,f
13908,b97aba90b14cb1b75063f726ec1fcf2e,2017,1,35000.0,Todo em escola particular,f,f,f,f
13909,77d7916c350e1c64ef6edaaa2c1814f2,2017,1,1000.0,Todo em escola publica,f,f,f,f
13910,4daff606d6a8847d933fd5646d3aa16b,2017,1,7500.0,Todo em escola publica,f,t,f,f
13911,84a2c2eee4699bd1df029ed976edc27b,2017,1,880.0,Todo em escola publica,f,t,f,f

In [4]:
dados_socio.pivot_table( index = 'escola_ens_medio', values='id_discente', aggfunc='count')

                                                    renda
escola_ens_medio
Em escola Particular, com bolsa                       783
Outro tipo de escola                                  145
Parte em escola pública parte em escola particu...    633
Todo em escola particular                            3457
Todo em escola publica                               8880

In [5]:
dados_socio.pivot_table( index = 'renda', values='id_discente', aggfunc='count')

              id_discente
renda
0.000000e+00           86
1.000000e+00           35
2.000000e+00           30
2.811000e+00            1
3.000000e+00            9
4.000000e+00           10
5.000000e+00            5
6.000000e+00            1
7.000000e+00            2
8.000000e+00            1
9.000000e+00            1
1.200000e+01            1
1.500000e+01            3
2.000000e+01            1
3.000000e+01            1
3.500000e+01            1
3.700000e+01            1
7.700000e+01            3
8.000000e+01            1
8.200000e+01            2
8.500000e+01            5
8.700000e+01            2
1.000000e+02            4
1.070000e+02            2
1.080000e+02            2
1.120000e+02            2
1.240000e+02            5
1.270000e+02            1
1.300000e+02            1
1.310000e+02            1
...                   ...
6.035640e+05            1
6.500000e+05            1
6.600000e+05            1
6.997100e+05            1
7.136000e+05            1
7.418100e+05            1
7.576040e+05            1
7.600000e+05            1
7.712400e+05            1
7.780000e+05            1
7.796010e+05            1
8.000000e+05            1
8.800310e+05            1
9.072060e+05            1
9.100000e+05            1
9.300000e+05            1
9.832240e+05            1
9.838500e+05            1
1.000000e+06            1
1.082574e+06            1
1.095219e+06            1
1.122395e+06            1
1.200000e+06            1
1.372781e+06            1
1.500000e+06            2
1.800000e+06            1
1.874000e+06            1
2.060074e+06            1
3.500000e+06            1
1.000000e+07            1

[2122 rows x 1 columns]